language: php
php:
  - 5.5
  - 5.6
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

script:
  - composer test tests

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  slack:
    rooms:
      secure: your_token_key