language: php
php:
  - 5.5.38
  - 5.6.9
  - 7.0.9
  - 7.1
  - 7.2

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

script:
  - composer test tests

after_script:
  - php vendor/bin/coveralls -v

notifications:
  slack:
    rooms:
      secure: your_token_key